export const SELECTOR_TYPES = {
  genre: [
    "adventure",
    "romance",
    "mystery",
    "fantasy",
    "science fiction",
    "horror",
    "historical fiction",
    "thriller",
    "comedy",
  ],
  theme: [
    "honesty",
    "kindness",
    "bravery",
    "perseverance",
    "compassion",
    "teamwork",
    "loyalty",
    "respect",
    "responsibility",
  ],
  ending: [
    "happy",
    "tragic",
    "cliffhanger",
    "bittersweet",
    "open",
    "surprise",
    "resolved",
    "unresolved",
    "ambiguous",
  ],
  age: ["0-2", "2-5", "6-9", "10-13", "14 +"],
  length: ["short", "shorter", "decent", "longer", "long"],
};
