export const SELECTOR_DATA = {
  STORY_TYPES: [
    "adventure",
    "romance",
    "mystery",
    "fantasy",
    "science fiction",
    "horror",
    "historical fiction",
    "thriller",
    "comedy",
  ],
  MORALS: [
    "honesty",
    "kindness",
    "bravery",
    "perseverance",
    "compassion",
    "teamwork",
    "loyalty",
    "respect",
    "responsibility",
  ],
  ENDING_TYPES: [
    "happy",
    "tragic",
    "cliffhanger",
    "bittersweet",
    "open",
    "surprise",
    "resolved",
    "unresolved",
    "ambiguous",
  ],
  AGE_SELECTOR: ["0-2", "2-5", "6-9", "10-13", "fine, it's not for my child"],
  STORY_LENGTH: [
    "super quick",
    "kinda quick",
    "whatever average means",
    "chill",
    "really chill",
  ],
};
